// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CameraScannerController from "./camera_scanner_controller"
application.register("camera-scanner", CameraScannerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import QrCodeController from "./qr_code_controller"
application.register("qr-code", QrCodeController)

import ScannerController from "./scanner_controller"
application.register("scanner", ScannerController)
